(function(a){a.exports("urlRE",RegExp("^(?:(?:https?)?:?//)?(?:(?!(?:10|127)(?:\\.\\d{1,3}){3})(?!(?:169\\.254|192\\.168)(?:\\.\\d{1,3}){2})(?!172\\.(?:1[6-9]|2\\d|3[0-1])(?:\\.\\d{1,3}){2})(?:[1-9]\\d?|1\\d\\d|2[01]\\d|22[0-3])(?:\\.(?:1?\\d{1,2}|2[0-4]\\d|25[0-5])){2}(?:\\.(?:[1-9]\\d?|1\\d\\d|2[0-4]\\d|25[0-4]))|(?:(?:[a-z\\u00a1-\\uffff0-9]-*)*[a-z\\u00a1-\\uffff0-9]+)(?:\\.(?:[a-z\\u00a1-\\uffff0-9]-*)*[a-z\\u00a1-\\uffff0-9]+)*(?:\\.(?:[a-z\\u00a1-\\uffff]{2,})))(?::\\d{2,5})?(?:(?:/|\\?)\\S*)?$",
"i"))})(LIModules);(function(c){var l=c.requires("jquery"),f=c.requires("underscore"),e;e=c.requires("BaseControl").extend(function(c){var n="placeholder"in document.createElement("input"),m={placeholderClass:"placeholder",preserveAttributes:"class id name tabindex title placeholder".split(" "),clearOnFormSubmit:!1};return{init:function(a,k){var b=l(a),d=b.find(':input:not(:submit):not([type\x3d"hidden"])'),g=d.length;this.$input=b;if(g){for(b=0;b<g;b++)new e(d[b],k);return!1}if(!b.is(":input:not(:submit)")||void 0===
b.attr("placeholder"))return!1;(!n||k&&k.forcePlaceholderSupported)&&c.init.apply(this,arguments)},beforeDecoration:function(){this.$input=this._$el;this.$form=this.$input.closest("form");f.union(m.preserveAttributes,this._config.preserveAttributes);this._config=f.defaults(this._config,m);this.inputType=this.$input.attr("type");this.placeholderText=this.$input.attr("placeholder");""===this.$input.val()&&this._addPlaceholderClass();"password"===this.inputType&&this._generateField("text",!1,!1);this.$form&&
this._config.clearOnFormSubmit&&this.attachFormListener()},afterDecoration:function(){"password"!==this.inputType&&""===this.$input.val()&&this.$input.val(this.placeholderText)},attachEventListeners:function(){if("password"===this.inputType)this.$input.on("focus blur",this._onPassword);else this.$input.on("focus blur paste",this._onText)},attachFormListener:function(){var a;this.$form.off("submit.placeholder-toggle").on("submit.placeholder-toggle",f.bind(function(){a=this.$form.find("."+this._config.placeholderClass);
a.length&&a.val("")},this))},_onText:function(a){"focus"===a.type&&this.$input.val()===this.placeholderText&&(this._removePlaceholderClass(),this.$input.val(""));"blur"===a.type&&""===this.$input.val()&&(this._addPlaceholderClass(),this.$input.val(this.placeholderText))},_onPassword:function(a){"focus"===a.type&&(this.$input.val()===this.placeholderText&&"text"===this.$input.attr("type"))&&(this._generateField("password",!0,!0),this._removePlaceholderClass());"blur"===a.type&&""===this.$input.val()&&
(this._generateField("text",!1,!0),this._addPlaceholderClass())},_generateField:function(a,c,b){var d=l('\x3cinput type\x3d"'+a+'" /\x3e'),g=this._config.preserveAttributes,f=g.length,e,h;for(h=0;h<f;h++)e=g[h],d.attr(e,this.$input.attr(e));this.$input.replaceWith(d);this.$input=d;"text"===a&&d.val(this.placeholderText);b&&this.attachEventListeners();c&&setTimeout(function(){d.focus()},0)},_addPlaceholderClass:function(){this.$input.addClass(this._config.placeholderClass)},_removePlaceholderClass:function(){this.$input.removeClass(this._config.placeholderClass)}}});
c.exports("Placeholder",e)})(window.LIModules);(function(){var e=LIModules.requires("underscore"),f=LIModules.requires("jquery"),d;d=LIModules.imports("BaseControl").extend(function(d){var g={url:null,popupWidth:790,popupHeight:580,scope:window,handleClickManual:!1,useNewGenie:!1};return{afterDecoration:function(){var a,c;c=(new Date).getTime();this._config=e.defaults(this._config,g);this._thisModule=this;if(!this._config.url)if(this._$el.is("a"))this._config.url=this._$el.attr("href");else throw Error("No URL was supplied and no URL was found in the control.");
a=function(a){var b=a;e.isString(a)&&(b=LIModules.imports(a));return b};this._config.onAllow=a(this._config.onAllow);if(!this._config.onAllow)throw Error("onAllow could not be found or resolved");this._config.onDeny=a(this._config.onDeny);if(!this._config.onDeny)throw Error("onDeny could not be found or resolved");this._config.onError=a(this._config.onError);if(!this._config.onError)throw Error("onError could not be found or resolved");this._config.onClose=a(this._config.onClose);if(!this._config.onClose)throw Error("onClose could not be found or resolved");
if("window"!==this._config.scope&&this._config.scope!==window&&(this._config.scope=a(this._config.scope),!this._config.scope))throw Error("scope could not be found or resolved");this._WINDOW_CALLBACK="oid_cb_"+c;this._WINDOW_CALLBACK_ALLOW=this._WINDOW_CALLBACK+"_allow";this._WINDOW_CALLBACK_DENY=this._WINDOW_CALLBACK+"_deny";this._WINDOW_CALLBACK_ERROR=this._WINDOW_CALLBACK+"_error";this._WINDOW_CALLBACK_CLOSE=this._WINDOW_CALLBACK+"_close";this._SCOPE_VAR=this._WINDOW_CALLBACK+"_scope";c=JSON.stringify({onAllow:this._WINDOW_CALLBACK_ALLOW,
onDeny:this._WINDOW_CALLBACK_DENY,onError:this._WINDOW_CALLBACK_ERROR,onClose:this._WINDOW_CALLBACK_CLOSE,scope:this._SCOPE_VAR});if(this._config.useNewGenie){a=this._getQueryParams(this._config.url.split("?")[1]).url;if(!a)throw Error("New Genie requires a returnUrl param in the genie url");a=this._addQueryParam(a,"cb",c);this._config.url=this._addQueryParam(this._config.url,"url",a)}else this._config.url=this._addQueryParam(this._config.url,"cb",c)},attachEventListeners:function(){if(!this._config.handleClickManual)this._$el.on("click",
this.handleClick)},cleanupWindowCallbacks:function(){window[this._WINDOW_CALLBACK_ALLOW]=null;window[this._WINDOW_CALLBACK_DENY]=null;window[this._WINDOW_CALLBACK_ERROR]=null;window[this._WINDOW_CALLBACK_CLOSE]=null;window[this._SCOPE_VAR]=null;this._windowLaunched=!1;clearInterval(this._windowInterval);this._windowInterval=null},createWindowCallbacks:function(){window[this._WINDOW_CALLBACK_ALLOW]=function(a){this.cleanupWindowCallbacks();this._config.onAllow.call(this._config.scope,a,this._config.obj)};
window[this._WINDOW_CALLBACK_DENY]=function(a){this.cleanupWindowCallbacks();this._config.onDeny.call(this._config.scope,a,this._config.obj)};window[this._WINDOW_CALLBACK_ERROR]=function(a){this.cleanupWindowCallbacks();this._config.onError.call(this._config.scope,a,this._config.obj)};window[this._WINDOW_CALLBACK_CLOSE]=function(a){this.cleanupWindowCallbacks();this._config.onClose.call(this._config.scope,a,this._config.obj)};window[this._SCOPE_VAR]=this._thisModule},handleClick:function(a){this.createWindowCallbacks();
this._popupWindow?this._popupWindow.focus():this._popupWindow=this._createPopupWindow();this._windowLaunched=!0;this._windowInterval=setInterval(e.bind(this._closeWindow,this),300)},_createPopupWindow:function(){return window.open(this._config.url,"genie_popup","width\x3d"+this._config.popupWidth+",height\x3d"+this._config.popupHeight)},_closeWindow:function(){this._windowLaunched&&(this._popupWindow&&this._popupWindow.closed)&&(this.cleanupWindowCallbacks(),this._config.onClose.call(this._config.scope,
{},this._config.obj),this._popupWindow=null)},_getQueryParams:function(a){var c={};a&&(a=a.split("\x26"),f.each(a,function(a,b){b=b.split("\x3d");b[0]=decodeURIComponent(b[0]);c[b[0]]=b[1]?decodeURIComponent(b[1]):null}));return c},_addQueryParam:function(a,c,e){var b;a=(a||"").split("?");a={base:a[0],query:a[1]||""};b=this._getQueryParams(a.query);b[c]=e;a.query="";for(var d in b)a.query&&(a.query+="\x26"),a.query+=encodeURIComponent(d)+"\x3d"+encodeURIComponent(b[d]);return a.base+"?"+a.query}}});
LIModules.exports("Genie",d)})();